version: "3.8"

services:
  nats:
    image: nats-streaming:latest
    command: --config /etc/nats/nats-main.conf --user sys
    volumes:
      - ${PWD}/conf/nats-main.conf:/etc/nats/nats-main.conf
    ports:
      - "4222:4222"

  natsleaf_a:
    image: nats-streaming:latest
    command: --config /etc/nats/nats-leaf-a.conf --user a
    volumes:
      - ${PWD}/conf/nats-leaf-a.conf:/etc/nats/nats-leaf-a.conf
    ports:
      - "4223:4222"
    depends_on:
      - nats

  natsleaf_b:
    image: nats-streaming:latest
    command: --config /etc/nats/nats-leaf-b.conf --user b
    volumes:
      - ${PWD}/conf/nats-leaf-b.conf:/etc/nats/nats-leaf-b.conf
    ports:
      - "4224:4222"
    depends_on:
      - nats
